# apiVersion: v1
# kind: Pod
# metadata:
#   name: inventory-service
#   labels:
#     app: inventory-service
# spec:
#   containers:
#   - name: inventory-service
#     image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:latest
#     ports:
#     - containerPort: 8080

#apiVersion: v1
#kind: ReplicationController
#metadata:
# name: inventory-service
#spec:
# replicas: 2
# selector:
#   app: inventory-service
# template:
#   metadata:
#     name: inventory-service
#     labels:
#       app: inventory-service
#   spec:
#     containers:
#     - name: inventory-service
#       image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:latest
#       ports:
#       - containerPort: 8080

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: inventory-service-deployment
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  strategy:
    type: Recreate
  template:
    metadata:
      name: inventory-service
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:8
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30082
  selector:
    app: inventory-service