# apiVersion: v1
# kind: Pod
# metadata:
#   name: inventory-service
#   labels:
#     app: inventory-service
# spec:
#   containers:
#   - name: inventory-service
#     image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:latest
#     ports:
#     - containerPort: 8080
apiVersion: v1
kind: ReplicationController
metadata:
  name: inventory-server
spec:
  replicas: 2
  selector:
    app: inventory-server
  template:
    metadata:
      name: inventory-server
      labels:
        app: inventory-server
    spec:
      containers:
      - name: inventory-server
        image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
    nodePort: 30081
  selector:
    app: inventory-service